export const coffees = [
  {
    img: 'https://imgur.com/LgTeZrp.png',
    name: 'Expresso Tradicional',
    tag: 'TRADICIONAL',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/Gy4gWTa.png',
    name: 'Expresso Americano',
    tag: 'TRADICIONAL',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/K3IcOel.png',
    name: 'Expresso Cremoso',
    tag: 'TRADICIONAL',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/UFveUDt.png',
    name: 'Expresso Gelado',
    tag: 'TRADICIONAL',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/qUzm5Nv.png',
    name: 'Café com Leite',
    tag: 'TRADICIONAL',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/C08F21x.png',
    name: 'Latte',
    tag: 'TRADICIONAL',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/sSSWlEi.png',
    name: 'Capuccino',
    tag: 'TRADICIONAL',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/l5rKNiE.png',
    name: 'Macchiato',
    tag: 'TRADICIONAL',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/Tpyc09f.png',
    name: 'Mocaccino',
    tag: 'TRADICIONAL',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/rYcx2Ut.png',
    name: 'Chocolate Quente',
    tag: 'ESPECIAL',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/ZS2BrDH.png',
    name: 'Cubano',
    tag: 'ESPECIAL',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/UkeuEah.png',
    name: 'Havaiano',
    tag: 'ESPECIAL',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/wMEjjrP.png',
    name: 'Árabe',
    tag: 'ESPECIAL',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 4.0,
    amount: 0,
  },
  {
    img: 'https://imgur.com/WXlT5e3.png',
    name: 'Irlandês',
    tag: 'ESPECIAL',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 4.0,
    amount: 0,
  },
]
